force-app/main/default/objects/Feature_Layers__mdt/Feature_Layers__mdt.object-meta.xml
<CustomObject>
    <label>Feature Layer</label>
    <pluralLabel>Feature Layers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Layers__mdt/fields/popupTemplate__c.field-meta.xml
<CustomField>
    <fullName>popupTemplate__c</fullName>
    <label>popupTemplate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feature_Layers__mdt/fields/renderer__c.field-meta.xml
<CustomField>
    <fullName>renderer__c</fullName>
    <label>renderer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feature_Layers__mdt/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Feature_Layers__mdt/fields/visible__c.field-meta.xml
<CustomField>
    <fullName>visible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Polygon/fields/Altered_Data__c.field-meta.xml
<CustomField>
    <fullName>Altered_Data__c</fullName>
    <description>Used to store the altered polygon data if Reviewer has made some modifications.</description>
    <label>Altered Data</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/Polygon_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is Junction Object between Authorization Location Access Schedule &amp; Polygon to correctly map the time duration of polygon.</description>
    <label>Polygon Schedule</label>
    <nameField>
        <label>Polygon Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polygon Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Polygon_Schedule__c/fields/BLA_Id__c.field-meta.xml
<CustomField>
    <fullName>BLA_Id__c</fullName>
    <description>To hold the Id of the BLA associated with</description>
    <label>BLA Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Polygon__c.field-meta.xml
<CustomField>
    <fullName>Polygon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Polygon</label>
    <referenceTo>Polygon</referenceTo>
    <relationshipLabel>Polygon Schedules</relationshipLabel>
    <relationshipName>Polygon_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Review_Completed__c.field-meta.xml
<CustomField>
    <fullName>Review_Completed__c</fullName>
    <description>This is to capture whether the Reviewer has completed the review of the record.</description>
    <formula>OR(
ISPICKVAL( Status__c, &apos;Approved&apos;),
ISPICKVAL(Status__c, &apos;Rejected&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Review Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It captures the status of the polygon drawn for a particular time duration.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Reviewed</fullName>
                <default>true</default>
                <label>To Be Reviewed</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utils__mdt/Utils__mdt.object-meta.xml
<CustomObject>
    <label>Utils</label>
    <pluralLabel>Utils</pluralLabel>
</CustomObject>

BasicMap/classes/Basic_Map_Reviewer_Approval_Ctr.cls
public with sharing class Basic_Map_Reviewer_Approval_Ctr {
    public String apiKey{get;set;}
    
    public String featureLayers{get; set;}
    
    public String baseMapLayer{get;set;}
    
    public String communityUrl{get;set;}
    public String internalUrl{get;set;}
    
    public String validPolygonStyle{get;set;}
    public String invalidPolygonStyle{get;set;}
    
    public String validPolygonColor{get;set;}
    public String validPolygonOutLineColor{get;set;}
    public String invalidPolygonColor{get;set;}
    public String invalidPolygonOutLineColor{get;set;}
    public String reviewerOtherPolygonsOutlineColor{get;set;}
    public String reviewerCurrentPolygonOutlineColor{get;set;}
    
    public String polySchRecId{get; set;}
    public String strCurPolyRec {get;set;}
        
    public String strLatitude {get; set;}
    public String strLongitude {get; set;}
    
    String strRecId;
    public String strData {get; set;}
    public String strPolygonUpdStatus {get; set;}
    public String strAcceptedValues {get; set;}
    public string lexOrigin {get{ 
        return URL.getOrgDomainUrl().toExternalForm().split('.my.')[0]+'.lightning.force.com';
    } set;}
    
    public Basic_Map_Reviewer_Approval_Ctr(){
        // Get api Key
        apiKey = utils__mdt.getInstance('ApiKey').Value__c;
        system.debug(URL.getOrgDomainUrl().toExternalForm().split('.my.')[0]+'.lightning.force.com');
        baseMapLayer = utils__mdt.getInstance('ReviewerBaseMapLayer').Value__c;
        
        // Get Polygon Styles
        validPolygonStyle = utils__mdt.getInstance('validPolygonStyle').Value__c;
        invalidPolygonStyle = utils__mdt.getInstance('InvalidPolygonStyle').Value__c;
        
        // Get Polygon Colors
        validPolygonColor = utils__mdt.getInstance('ValidDrawnPolygonColor').Value__c;
        validPolygonOutLineColor = utils__mdt.getInstance('ValidDrawnPolygonOutLineColor').Value__c;
        invalidPolygonColor = utils__mdt.getInstance('InvalidDrawnPolygonColor').Value__c;
        invalidPolygonOutLineColor = utils__mdt.getInstance('InvalidDrawnPolygonOutLineColor').Value__c;
        reviewerOtherPolygonsOutlineColor = utils__mdt.getInstance('ReviewerOtherPolygonsOutlineColor').Value__c;
        reviewerCurrentPolygonOutlineColor = utils__mdt.getInstance('ReviewerCurrentPolygonOutlineColor').Value__c;
        
        strAcceptedValues = Utils__mdt.getInstance('PS_Approved_Status').Value__c;
        // Get Site url
        Site s = [SELECT Id, Name FROM Site where Name =: utils__mdt.getInstance('SiteName').Value__c];
        SiteDetail sd = [select SecureURL from SiteDetail where DurableId =: s.Id];
        communityUrl = sd.SecureURL.removeEnd('/');
        
        // Internal URL
        internalUrl = 'https://'+ URL.getOrgDomainUrl().getHost().split('\\.')[0].toLowerCase()+ '.lightning.force.com';
        
        // Get Feature Layers
        featureLayers = JSON.serialize([SELECT Id, url__c, visible__c, renderer__c, popupTemplate__c FROM Feature_Layers__mdt WHERE url__c != NULL WITH SECURITY_ENFORCED]);
        
        // Get Polygon Schedule Records
        String BLAId = ApexPages.currentPage().getParameters().get('recordId');
        Polygon_Schedule__c objSch = [SELECT Polygon__c, Polygon__r.Data, Polygon__r.Altered_Data__c, Id
                                                FROM Polygon_Schedule__c WHERE BLA_Id__c =: BLAId WITH SECURITY_ENFORCED LIMIT 1];
                                                
        polySchRecId = objSch.Id;
                                            
        strCurPolyRec = JSON.serialize(objSch);
        
        Schema.AuthApplicationPlace placeLoc = [SELECT PlaceId from AuthApplicationPlace WHERE RgltyAuthApplicationId =: BLAId WITH SECURITY_ENFORCED];
        String strPlaceId = String.ValueOf(placeLoc.PlaceId);
        
        Schema.Location objLoc = [SELECT Latitude, Longitude FROM Location WHERE Id =: strPlaceId WITH SECURITY_ENFORCED];
        strLatitude = String.ValueOf(objLoc.Latitude);
        strLongitude = String.ValueOf(objLoc.Longitude);
        strRecId = objSch.Polygon__c;

    }
    
   
    
    @AuraEnabled
    public static void updateScheduleStatus(Id recordId, String statusVal){
        Polygon_Schedule__c objPS = new Polygon_Schedule__c();
        objPS.Status__c = statusVal;
        objPS.Id = recordId;
        try {
            SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.UPDATABLE, new List<Polygon_Schedule__c>{objPS});
            update securityDecision.getRecords();
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    
    @AuraEnabled
    public static Polygon_Schedule__c getPolygonSchedule(String recordId) {
            
        return [SELECT Id, Polygon__c, Polygon__r.Data,
                Status__c,
                Review_Completed__c
                FROM Polygon_Schedule__c 
                WHERE 
                BLA_Id__c =: recordId WITH SECURITY_ENFORCED LIMIT 1];
    }
    
    @AuraEnabled
    public static String fetchVFDomainURL(){
        String strURL = 'https://'+DomainCreator.getVisualforceHostname('');
        return strURL;
    }
    
    public void updatePolygon(){
        try {
            Polygon objP = new Polygon();
            system.debug(strData);
            objP.Altered_Data__c = strData;
            objP.Id = strRecId;
            SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.UPDATABLE, new List<Polygon>{objP});
            update securityDecision.getRecords();
            strPolygonUpdStatus = 'Update succesful';
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, e.getMessage()));
        }
    }
}