force-app/main/default/objects/Polygon/fields/Altered_Data__c.field-meta.xml
<CustomField>
    <fullName>Altered_Data__c</fullName>
    <description>Used to store the altered polygon data if Reviewer has made some modifications.</description>
    <label>Altered Data</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/Polygon_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is Junction Object between Authorization Location Access Schedule &amp; Polygon to correctly map the time duration of polygon.</description>
    <label>Polygon Schedule</label>
    <nameField>
        <label>Polygon Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polygon Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Polygon_Schedule__c/fields/Authorization_Location_Access_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Location_Access_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorization Location Access Schedule</label>
    <referenceTo>AuthLocationAccessSchedule</referenceTo>
    <relationshipLabel>Polygon Schedules</relationshipLabel>
    <relationshipName>Polygon_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Business_License__c.field-meta.xml
<CustomField>
    <fullName>Business_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only when the record is approved and its associated Business License Application is also approved.</description>
    <label>Business License</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Polygon Schedules</relationshipLabel>
    <relationshipName>Polygon_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>This stores the comments provided by Reviewer.</description>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Polygon__c.field-meta.xml
<CustomField>
    <fullName>Polygon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Polygon</label>
    <referenceTo>Polygon</referenceTo>
    <relationshipLabel>Polygon Schedules</relationshipLabel>
    <relationshipName>Polygon_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It captures the status of the polygon drawn for a particular time duration.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Reviewed</fullName>
                <default>true</default>
                <label>To Be Reviewed</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utils__mdt/Utils__mdt.object-meta.xml
<CustomObject>
    <label>Utils</label>
    <pluralLabel>Utils</pluralLabel>
</CustomObject>

force-app/main/default/classes/Applicant_License_Approved_Ctr.cls
public without sharing class Applicant_License_Approved_Ctr { // Query: Sharing False Positive: the class job is to retrieve all the polygon records regardless of user permissions
    public String apiKey{get;set;}
    
    public String baseMapLayer{get;set;}
    
    public String outLineColor{get;set;}
    
    Id polySchRecId;
    public String strCurPolyRec {get;set;}
    
    public String strLatitude {get; set;}
    public String strLongitude {get; set;}
    
    public Applicant_License_Approved_Ctr(){
        // Get api Key
        apiKey = utils__mdt.getInstance('ApiKey').Value__c;
        
        baseMapLayer = utils__mdt.getInstance('LicenseApprovedBaseMapLayer').Value__c;
        
        // Get Business License Approved Polygon Outline Color
        outLineColor = utils__mdt.getInstance('LicenseApprovedPolygonOutlineColor').Value__c;
        
        String parameterValue = ApexPages.currentPage().getParameters().get('authLocationId');
		List<Polygon_Schedule__c> objSch = [SELECT Status__c,Comments__c,Polygon__c, Polygon__r.Data,Polygon__r.Altered_Data__c,
                                                Authorization_Location_Access_Schedule__r.AuthStartDate,
                                                Authorization_Location_Access_Schedule__r.AuthEndDate, 
                                                Authorization_Location_Access_Schedule__r.WorkStartTime, 
                                                Authorization_Location_Access_Schedule__r.WorkEndTime,
                                                Authorization_Location_Access_Schedule__r.AuthApplPlace.PlaceId
                                                FROM Polygon_Schedule__c 
                                                WHERE Authorization_Location_Access_Schedule__c =: parameterValue 
                                                AND Status__c =: utils__mdt.getInstance('PS_Approved_Status').Value__c];
        strCurPolyRec = JSON.serialize(objSch);
        if(!objSch.isEmpty()) {
            Schema.Location objLoc = [SELECT Latitude, Longitude FROM Location WHERE Id =: objSch[0].Authorization_Location_Access_Schedule__r.AuthApplPlace.PlaceId];
            strLatitude = String.ValueOf(objLoc.Latitude);
            strLongitude = String.ValueOf(objLoc.Longitude);
        }
    }
    
    @AuraEnabled
    public static List<String> getLocationchedules(String recordId) {
        Set<String> authLocationAccessScheduleIdSet = new Set<String>();
        for(Polygon_Schedule__c ps : [SELECT Id,Status__c,Authorization_Location_Access_Schedule__c,Business_License__c
                                      FROM Polygon_Schedule__c 
                                      WHERE Business_License__c =: recordId AND Status__c = 'Approved']) {
            authLocationAccessScheduleIdSet.add(ps.Authorization_Location_Access_Schedule__c);
        }
        return new List<String>(authLocationAccessScheduleIdSet);
    }
}