force-app/main/default/objects/Polygon/fields/Altered_Data__c.field-meta.xml
<CustomField>
    <fullName>Altered_Data__c</fullName>
    <description>Used to store the altered polygon data if Reviewer has made some modifications.</description>
    <label>Altered Data</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/Polygon_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is Junction Object between Authorization Location Access Schedule &amp; Polygon to correctly map the time duration of polygon.</description>
    <label>Polygon Schedule</label>
    <nameField>
        <label>Polygon Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polygon Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Polygon_Schedule__c/fields/BLA_Id__c.field-meta.xml
<CustomField>
    <fullName>BLA_Id__c</fullName>
    <description>To hold the Id of the BLA associated with</description>
    <label>BLA Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>This stores the comments provided by Reviewer.</description>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Polygon__c.field-meta.xml
<CustomField>
    <fullName>Polygon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Polygon</label>
    <referenceTo>Polygon</referenceTo>
    <relationshipLabel>Polygon Schedules</relationshipLabel>
    <relationshipName>Polygon_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It captures the status of the polygon drawn for a particular time duration.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Reviewed</fullName>
                <default>true</default>
                <label>To Be Reviewed</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Utils__mdt/Utils__mdt.object-meta.xml
<CustomObject>
    <label>Utils</label>
    <pluralLabel>Utils</pluralLabel>
</CustomObject>

BasicMap/classes/Basic_Map_Ctr.cls
public with sharing class Basic_Map_Ctr {
    public String apiKey{get;set;}
    
    public String baseMapLayer{get;set;}
    
    public String outLineColor{get;set;}
    public String reviewerOtherPolygonsOutlineColor{get; set;}
    
    Id polySchRecId;
    public String strCurPolyRec {get;set;}
    
    public String strLatitude {get; set;}
    public String strLongitude {get; set;}
    
    public Basic_Map_Ctr(){
        // Get api Key
        apiKey = utils__mdt.getInstance('ApiKey').Value__c;
        
        baseMapLayer = utils__mdt.getInstance('ApplicantBaseMapLayer').Value__c;
        
        // Get Applicant Polygon Outline Color
        outLineColor = utils__mdt.getInstance('ApplicantPolygonOutLineColor').Value__c;
        reviewerOtherPolygonsOutlineColor = utils__mdt.getInstance('ReviewerOtherPolygonsOutlineColor').Value__c;
        
        String parameterValue = ApexPages.currentPage().getParameters().get('applicationId');
        List<Polygon_Schedule__c> objSch = [SELECT Status__c,Comments__c,Polygon__c, Polygon__r.Data, Polygon__r.Altered_Data__c
                                                FROM Polygon_Schedule__c WHERE BLA_Id__c =: parameterValue WITH SECURITY_ENFORCED];
        strCurPolyRec = JSON.serialize(objSch);
        if(!objSch.isEmpty()) {
            Schema.AuthApplicationPlace placeLoc = [SELECT PlaceId from AuthApplicationPlace WHERE RgltyAuthApplicationId =: parameterValue WITH SECURITY_ENFORCED];
            String strPlaceId = String.ValueOf(placeLoc.PlaceId);
            
        
            Schema.Location objLoc = [SELECT Latitude, Longitude FROM Location WHERE Id =: strPlaceId WITH SECURITY_ENFORCED];
            strLatitude = String.ValueOf(objLoc.Latitude);
            strLongitude = String.ValueOf(objLoc.Longitude);
        }
    }
    

}