force-app/main/default/objects/BusinessLicenseApplication/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Polygon_Schedule__c/Polygon_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is Junction Object between Authorization Location Access Schedule &amp; Polygon to correctly map the time duration of polygon.</description>
    <label>Polygon Schedule</label>
    <nameField>
        <label>Polygon Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polygon Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Polygon_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It captures the status of the polygon drawn for a particular time duration.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Reviewed</fullName>
                <default>true</default>
                <label>To Be Reviewed</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Reviewer_Approval_CtrTest.cls
@isTest
public class Reviewer_Approval_CtrTest {
    @TestSetup
    static void setupData() {
        List<RegulatoryAuthorizationType> reglAuthTypeList = TestDataFactory.createReglAuthTypes(1,true,'event','License');
        List<BusinessLicenseApplication> blaList = TestDataFactory.createBlas(1,true,'Event',reglAuthTypeList[0].Id);
        List<Schema.Location> locationList = TestDataFactory.createLocations(1,true,'Loc-01','Site',-79,43);
        List<AuthApplicationPlace> authAppPlaceList = TestDataFactory.createAuthApplicationPlaces(1,true,blaList[0].Id,locationList[0].Id);
        List<AuthLocationAccessSchedule> authLocAccSchList = TestDataFactory.createAuthLocSchedules(1,true,authAppPlaceList[0].Id,Date.today(),System.now().time(),Date.today()+1,System.now().time());
        String polygonData = '{"spatialReference":{"latestWkid":3857,"wkid":102100},"rings":[[[-8848674.650861043,5422584.950330664],[-8848567.209164083,5422623.168844808],[-8848536.90499061,5422510.105716169],[-8848648.479060533,5422467.109887757],[-8848674.650861043,5422584.950330664]]]}';
        List<Polygon> polygonList = TestDataFactory.createPolygons(1,true,'PolyRecd','GEOJSON',polygonData);
        List<Polygon_Schedule__c> psList = TestDataFactory.createPolygonSchedules(2,true,'PS-01',polygonList[0].Id,authLocAccSchList[0].Id);
        List<Task> taskList = TestDataFactory.createTasks(1,true,'Map Review', blaList[0].Id, 'Not Started');
    }
    
    @isTest
    private static void unitTest() {
        Test.startTest();
            Polygon_Schedule__c ps = [SELECT Id FROM Polygon_Schedule__c LIMIT 1];
        
            PageReference pageRef = Page.Reviewer_Approval_Page;
            pageRef.getParameters().put('polySchId', String.valueOf(ps.Id));
            Test.setCurrentPage(pageRef);
        
        	Reviewer_Approval_Ctr obj = new Reviewer_Approval_Ctr();
       	 	obj.strData = '{"spatialReference":{"latestWkid":3857,"wkid":102100},"rings":[[[-8888888.650861043,9999999.950330664],[-8848567.209164083,5422623.168844808],[-8848536.90499061,5422510.105716169],[-8848648.479060533,5422467.109887757],[-8848674.650861043,5422584.950330664]]]}';
        	obj.updatePolygon();
        	System.Assert(obj.strPolygonUpdStatus == 'Update succesful');
        	System.Assert(obj.strCurPolyRec != null);
        	System.Assert(obj.strRelatedPolyRecs != null);
        Test.stopTest();
    }
    
    @isTest
    private static void updateScheduleStatusTest() {
        Test.startTest();	
        	Polygon_Schedule__c ps = [SELECT Id FROM Polygon_Schedule__c LIMIT 1];
        	Reviewer_Approval_Ctr.updateScheduleStatus(ps.Id, 'Approved');
        	System.Assert([SELECT Id, Status__c FROM Polygon_Schedule__c WHERE Id =: ps.Id].Status__c == 'Approved');
        Test.stopTest();
    }
    
    @isTest
    private static void getPolySchdulesTest() {
        Test.startTest();	
        	Task t = [SELECT Id FROM Task LIMIT 1];
        	List<Polygon_Schedule__c> psList = Reviewer_Approval_Ctr.getPolySchdules(t.Id);
        	System.Assert(psList.size() > 0);
        Test.stopTest();
    }
    
    
}