force-app/main/default/objects/BusinessLicenseApplication/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Polygon_Schedule__c/Polygon_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is Junction Object between Authorization Location Access Schedule &amp; Polygon to correctly map the time duration of polygon.</description>
    <label>Polygon Schedule</label>
    <nameField>
        <label>Polygon Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polygon Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Polygon_Schedule__c/fields/Business_License__c.field-meta.xml
<CustomField>
    <fullName>Business_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only when the record is approved and its associated Business License Application is also approved.</description>
    <label>Business License</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Polygon Schedules</relationshipLabel>
    <relationshipName>Polygon_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Polygon_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>It captures the status of the polygon drawn for a particular time duration.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Reviewed</fullName>
                <default>true</default>
                <label>To Be Reviewed</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Applicant_License_Approved_CtrTest.cls
@isTest
public class Applicant_License_Approved_CtrTest {
    @TestSetup
    static void setupData() {
        List<Account> accList = TestDataFactory.createAccounts(1, true, 'test');
        List<Contact> conList = TestDataFactory.createContacts(1, true, 'test last name', accList[0].Id);
        User usr = TestDataFactory.createUser('Customer Community Plus User','applicantuser@test.com',conList[0].Id);
        System.runAs(new User(Id = Userinfo.getUserId())) {
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'ESRI_Community'];
            insert new PermissionSetAssignment(AssigneeId = usr.id, PermissionSetId = ps.Id);
        }
        system.runAs(usr) {
        	List<RegulatoryAuthorizationType> reglAuthTypeList = TestDataFactory.createReglAuthTypes(1,true,'event','License');
        	List<BusinessLicense> blList = TestDataFactory.createBusinessLicenses(1, true, 'test', reglAuthTypeList[0].Id);
            List<BusinessLicenseApplication> blaList = TestDataFactory.createBlas(1,true,'Event',reglAuthTypeList[0].Id);
            List<Schema.Location> locationList = TestDataFactory.createLocations(1,true,'Loc-01','Site',-79,43);
            List<AuthApplicationPlace> authAppPlaceList = TestDataFactory.createAuthApplicationPlaces(1,true,blaList[0].Id,locationList[0].Id);
            List<AuthLocationAccessSchedule> authLocAccSchList = TestDataFactory.createAuthLocSchedules(1,true,authAppPlaceList[0].Id,Date.today(),System.now().time(),Date.today()+1,System.now().time());
            String polygonData = '{"spatialReference":{"latestWkid":3857,"wkid":102100},"rings":[[[-8848674.650861043,5422584.950330664],[-8848567.209164083,5422623.168844808],[-8848536.90499061,5422510.105716169],[-8848648.479060533,5422467.109887757],[-8848674.650861043,5422584.950330664]]]}';
            List<Polygon> polygonList = TestDataFactory.createPolygons(1,true,'PolyRecd','GEOJSON',polygonData);
            List<Polygon_Schedule__c> psList = TestDataFactory.createPolygonSchedules(2,false,'PS-01',polygonList[0].Id,authLocAccSchList[0].Id);
            psList[0].Business_License__c = blList[0].Id;
            psList[1].Business_License__c = blList[0].Id;
            psList[0].Status__c = 'Approved';
            psList[1].Status__c = 'Approved';
            insert psList;
        }
    }
    
    @isTest
    private static void getLocationchedulesTest() {
        User usr = [SELECT Id FROM User where username = 'applicantuser@test.com'];
        System.runAs(usr) {
            Test.startTest();
                BusinessLicense bl = [SELECT Id FROM BusinessLicense LIMIT 1];
                List<String> result = Applicant_License_Approved_Ctr.getLocationchedules(bl.Id);
                System.Assert(result.size() > 0);
            Test.stopTest();
        }
    }
    
    @isTest
    private static void unitTest() {
        User usr = [SELECT Id FROM User where username = 'applicantuser@test.com'];
        System.runAs(usr) {
            Test.startTest();
            	AuthLocationAccessSchedule authLocScheduleList = [SELECT Id FROM AuthLocationAccessSchedule LIMIT 1];
            
                PageReference pageRef = Page.Applicant_License_Approved_Page;
                pageRef.getParameters().put('authLocationId', String.valueOf(authLocScheduleList.Id));
                Test.setCurrentPage(pageRef);
            
                Applicant_License_Approved_Ctr obj = new Applicant_License_Approved_Ctr();
            	System.Assert(obj.strCurPolyRec != NULL);
            	System.Assert(obj.strLatitude != NULL);
            Test.stopTest();
        }
    }
}